### ISSUE TITLE
Project 4 peer review

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/Schrodinger-s-cat#100]

**Comment by raghu2094** [comment]
Hey team,
Is there any link to view the Kubernetes dashboard?

**Comment by nawazkh** [comment]
Hello Raghu, 

Our application is up and running if you want to test it. 
The link is mentioned in the assignment 4. 

Also, you can check our dashboard for Kubernetes installation. You will need the admin token for login.
We will get it to you in personal chat once you ping us.

All the documentation and wiki will be done soon.

Thanks,
Nawaz

**Comment by raghu2094** [comment]
@nawazkh Hi Nawaz, I am not able to access the dashboard. Getting a "Your connection is not private" error

**Comment by nawazkh** [comment]
As per our communication, I think it is a security error. 
Since dashboard is a https application and we have implemented in a cluster with no SSL implementation, it is possible that the connection may not be private. And hence your browser is not letting you access the dashboard.

If you could try it from another browser, it would be great! 

Thanks,
Nawaz

**Comment by raghu2094** [comment]
Tested the application. Tried signup , login , search and add recipe. All features are working fine.
UI has been improved compared to previous assignments. Looks better.

Tested deployment by committing to the release branch. Replica sets are created which in turn create pods. Rolling updates is also achieved using Kubernetes.

Wiki is well documented with neat architecture diagrams and detailed description of the tasks the team has achieved over the course of  4 assignments.. 
In all , I feel a lot of effort has been put in project 4 and it shows in the tasks which the team have successfully accomplished. Congrats and well done.

**Comment by pswargam** [comment]
Thank you  Raghu.
