### ISSUE TITLE
Link FrontEnd links with LoginAuthentication Service

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#15]
Map Frontend's functionality with Login Authentication service
Done in 866ad3d4faef5be41945c3ef68556f04620b20fd

**Comment by pswargam** [comment]
Update the links in node and react server

**Comment by ljosyula** [comment]
completed this in: 48cf399d6da3d0e7b9aedcd35d1d445256baa5be
