### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/Schrodinger-s-cat#18]
* Napkin diagram clearly illustrates the purpose of building this application.
* Followed all the steps to start the application . Found few instructions missing such as in step 5 the directory inside which "mvn clean install" has to be executed is not mentioned. Also, the application starts at localhost:3000 and not localhost:3080 as mentioned in the README. Kindly update the README 
 * Was able to search recipes from the dashboard.
* Tried registering as a new user but it shows Signup failed message

**Comment by raghu2094** [comment]
Getting this error from Node server
Error: Request failed with status code 500
    at createError (/home/raghu2094/SGA-food1/Schrodinger-s-cat/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/raghu2094/SGA-food1/Schrodinger-s-cat/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/raghu2094/SGA-food1/Schrodinger-s-cat/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

Probably related to axios. Hope it helps.

**Comment by pswargam** [comment]
Thank Raghu,

We are looking into it

**Comment by pswargam** [comment]
Hi Raghu,

I have updated the instructions in readme.
Please pull the branch "frontEnd_React" and try again.
Let us know, if you face any issues.

Thanks
Prashanth

**Comment by raghu2094** [comment]
{ firstName: 'raghya',
  lastName: 'talwai',
  email: 'raghu@gmail.com',
  username: 'raghu@gmail.com',
  password: 'test12345',
  selfDescription: 'student',
  recipeId: [] }
{ Error: Request failed with status code 500
    at createError (/home/raghu2094/food1/Schrodinger-s-cat/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/home/raghu2094/food1/Schrodinger-s-cat/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/home/raghu2094/food1/Schrodinger-s-cat/node_modules/axios/lib/adapters/http.js:201:11)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1092:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  config:
   { adapter: [Function: httpAdapter],
     transformRequest: { '0': [Function: transformRequest] },
     transformResponse: { '0': [Function: transformResponse] },
     timeout: 0,
     xsrfCookieName: 'XSRF-TOKEN',
     xsrfHeaderName: 'X-XSRF-TOKEN',
     maxContentLength: -1,
     validateStatus: [Function: validateStatus],
     headers:
      { Accept: 'application/json, text/plain, */*',
        'Content-Type': 'application/json;charset=utf-8',
        'User-Agent': 'axios/0.18.0',
        'Content-Length': 162 },
     method: 'post',
     url: 'http://localhost:8888/jpa/users/register',
     data:
      '{"firstName":"raghya","lastName":"talwai","email":"raghu@gmail.com","username":"raghu@gmail.com","password":"test12345","selfDescription":"student","recipeId":[]}' },
  request:
   ClientRequest {
     _events:
      { socket: [Function],
        abort: [Function],
        aborted: [Function],
        error: [Function],
        timeout: [Function],
        prefinish: [Function: requestOnPrefinish] },
     _eventsCount: 6,
     _maxListeners: undefined,
     output: [],
     outputEncodings: [],
     outputCallbacks: [],
     outputSize: 0,
     writable: true,
     _last: true,
     chunkedEncoding: false,
     shouldKeepAlive: false,
     useChunkedEncodingByDefault: true,
     sendDate: false,
     _removedConnection: false,
     _removedContLen: false,
     _removedTE: false,
     _contentLength: null,
     _hasBody: true,
     _trailer: '',
     finished: true,
     _headerSent: true,
     socket:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 16,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     connection:
      Socket {
        connecting: false,
        _hadError: false,
        _handle: [TCP],
        _parent: null,
        _host: 'localhost',
        _readableState: [ReadableState],
        readable: true,
        _events: [Object],
        _eventsCount: 7,
        _maxListeners: undefined,
        _writableState: [WritableState],
        writable: false,
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: null,
        _server: null,
        parser: null,
        _httpMessage: [Circular],
        [Symbol(asyncId)]: 16,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBytesRead)]: 0,
        [Symbol(kBytesWritten)]: 0 },
     _header:
      'POST /jpa/users/register HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 162\r\nHost: localhost:8888\r\nConnection: close\r\n\r\n',
     _onPendingData: [Function: noopPendingOutput],
     agent:
      Agent {
        _events: [Object],
        _eventsCount: 1,
        _maxListeners: undefined,
        defaultPort: 80,
        protocol: 'http:',
        options: [Object],
        requests: {},
        sockets: [Object],
        freeSockets: {},
        keepAliveMsecs: 1000,
        keepAlive: false,
        maxSockets: Infinity,
        maxFreeSockets: 256 },
     socketPath: undefined,
     timeout: undefined,
     method: 'POST',
     path: '/jpa/users/register',
     _ended: true,
     res:
      IncomingMessage {
        _readableState: [ReadableState],
        readable: false,
        _events: [Object],
        _eventsCount: 3,
        _maxListeners: undefined,
        socket: [Socket],
        connection: [Socket],
        httpVersionMajor: 1,
        httpVersionMinor: 1,
        httpVersion: '1.1',
        complete: true,
        headers: [Object],
        rawHeaders: [Array],
        trailers: {},
        rawTrailers: [],
        aborted: false,
        upgrade: false,
        url: '',
        method: null,
        statusCode: 500,
        statusMessage: '',
        client: [Socket],
        _consuming: true,
        _dumped: false,
        req: [Circular],
        responseUrl: 'http://localhost:8888/jpa/users/register',
        redirects: [] },
     aborted: undefined,
     timeoutCb: null,
     upgradeOrConnect: false,
     parser: null,
     maxHeadersCount: null,
     _redirectable:
      Writable {
        _writableState: [WritableState],
        writable: true,
        _events: [Object],
        _eventsCount: 2,
        _maxListeners: undefined,
        _options: [Object],
        _redirectCount: 0,
        _redirects: [],
        _requestBodyLength: 162,
        _requestBodyBuffers: [],
        _onNativeResponse: [Function],
        _currentRequest: [Circular],
        _currentUrl: 'http://localhost:8888/jpa/users/register' },
     [Symbol(isCorked)]: false,
     [Symbol(outHeadersKey)]:
      { accept: [Array],
        'content-type': [Array],
        'user-agent': [Array],
        'content-length': [Array],
        host: [Array] } },
  response:
   { status: 500,
     statusText: '',
     headers:
      { 'x-content-type-options': 'nosniff',
        'x-xss-protection': '1; mode=block',
        'cache-control': 'no-cache, no-store, max-age=0, must-revalidate',
        pragma: 'no-cache',
        expires: '0',
        'content-type': 'application/json;charset=UTF-8',
        'transfer-encoding': 'chunked',
        date: 'Tue, 25 Sep 2018 04:46:25 GMT',
        connection: 'close' },
     config:
      { adapter: [Function: httpAdapter],
        transformRequest: [Object],
        transformResponse: [Object],
        timeout: 0,
        xsrfCookieName: 'XSRF-TOKEN',
        xsrfHeaderName: 'X-XSRF-TOKEN',
        maxContentLength: -1,
        validateStatus: [Function: validateStatus],
        headers: [Object],
        method: 'post',
        url: 'http://localhost:8888/jpa/users/register',
        data:
         '{"firstName":"raghya","lastName":"talwai","email":"raghu@gmail.com","username":"raghu@gmail.com","password":"test12345","selfDescription":"student","recipeId":[]}' },
     request:
      ClientRequest {
        _events: [Object],
        _eventsCount: 6,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: true,
        sendDate: false,
        _removedConnection: false,
        _removedContLen: false,
        _removedTE: false,
        _contentLength: null,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Socket],
        connection: [Socket],
        _header:
         'POST /jpa/users/register HTTP/1.1\r\nAccept: application/json, text/plain, */*\r\nContent-Type: application/json;charset=utf-8\r\nUser-Agent: axios/0.18.0\r\nContent-Length: 162\r\nHost: localhost:8888\r\nConnection: close\r\n\r\n',
        _onPendingData: [Function: noopPendingOutput],
        agent: [Agent],
        socketPath: undefined,
        timeout: undefined,
        method: 'POST',
        path: '/jpa/users/register',
        _ended: true,
        res: [IncomingMessage],
        aborted: undefined,
        timeoutCb: null,
        upgradeOrConnect: false,
        parser: null,
        maxHeadersCount: null,
        _redirectable: [Writable],
        [Symbol(isCorked)]: false,
        [Symbol(outHeadersKey)]: [Object] },
     data:
      { timestamp: '2018-09-25T04:46:25.354+0000',
        message: null,
        details: 'uri=/jpa/users/register' } } }




@pswargam Tried a fresh clone and installed everything from scratch. 
Getting the same error from Node. Please have a look

**Comment by pswargam** [comment]
Hi Raghu,

We are looking into it.

Thanks
Prashanth

**Comment by raghu2094** [comment]
Hi Team, 
Issue seems to be resolved . I am able to signup as new user and login using the credentials. All microservices are working fine.
Pushed commits to check if Travis CI triggering automatic builds. All builds passed.
Good Job!
Regards,
Raghottam

**Comment by nawazkh** [comment]
Achieved in this 6360357a8fc191f9dde28830c00a4b9515ce3427
