### ISSUE TITLE
Maven build failed

### ISSUE THREAD

**Issue by siddharthpathak** [airavata-courses/Schrodinger-s-cat#19]
Not able to build Maven after doing `mvn clean install`. 

Getting the below error:

```
Java.lang.IllegalStateExecption: failed to load ApplicationContext
```

It is failing the test cases. I have all the microservices running.

**Comment by nawazkh** [comment]
Hello Siddharth, 

Can you please update the issue with the logs? 
I think there might have been a setup issue here.

**Comment by siddharthpathak** [comment]
Hi,

I am not able to paste logs in a proper format, but I wlll post an image instead. 

![index](https://user-images.githubusercontent.com/11479211/45995239-3e0bf100-c065-11e8-83ab-5e4c2b4b216e.jpg)

Sorry for bad quality, VM is not letting me take a proper screenshot. Let me know if you need more information. 
I was able to follow all the steps correctly, and there was no error till the maven part.

**Comment by nawazkh** [comment]
Hello @siddharthpathak ,

Error was with java version being used here. We have added the dependency and committed it to the branch.
Please pull a fresh commit from feature-login_authentication branch.

-Nawaz

**Comment by siddharthpathak** [comment]
Thanks Nawaz, I was able to run the application after pulling in the changes.

**Comment by nawazkh** [comment]
Achieved this in 2c11b3cf26619305b7cb18b9a73a3f6d32d18b06
