### ISSUE TITLE
Few suggestions

### ISSUE THREAD

**Issue by siddharthpathak** [airavata-courses/Schrodinger-s-cat#20]
Few suggestions/questions: 
1. The sign up UI doesn't display an error if the field size is less than 7. if it is less than 7, it allows to sign up but not login. Having a error message pop up would make it more user friendly.

2. After searching for recipes, it doesn't reset to default view if the search text box is cleared. For e.g if I search for `egg` it gives the results, but I can't view the default list again unless the page is refreshed. 

3. The architecture diagram mentions the use of rabbit MQ. I didn't where it is used right now, or is it a part of future release? 

Everything else works as expected!

**Comment by nawazkh** [comment]
Thank you for the update @siddharthpathak , We will look into it and update the code.
1. We will update the change soon. Just need to add a check to the front end component.
2. Data being queried must be cleared on search box being empty, Have created its issue.
3. Rabbit MQ is a part of future release, we have not implemented it as of now.
