### ISSUE TITLE
Peer Review results

### ISSUE THREAD

**Issue by sagarpanchal8793** [airavata-courses/Schrodinger-s-cat#21]
1. Tested the entire application using the link (http://149.160.182.24:3000) and everything was working perfectly. Created an account and logged in successfully.

2. Verified the architecture diagram on the Wiki

3. Performed commits in all the branches to test whether Travis CI build is successful or not and yes, all the builds were successful. Below is the snapshot of the same.

![image](https://user-images.githubusercontent.com/32082819/46053542-51749600-c111-11e8-8e5c-d62a46ab0174.png)

Everything LGTM, great efforts and keep up the good work!

**Comment by nawazkh** [comment]
Thank you for the Sign Off! @sagarpanchal8793 
Achieved this in 094462e9b89a6f695dd7808f24d88dcc146e9665
