### ISSUE TITLE
Enable RabbitMQ for Login Authentication Microservice

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#24]
Need to integrate RabbitMQ for Login Authentication

**Comment by nawazkh** [comment]
Achieved by faa44af658c166ac9fc71fb58a1841ec1e1e2328

**Comment by pswargam** [comment]
Used an existing image from management:rabbitmq to build the image.
Necessary ports were exposed.
Later integration with existing maven application is done by Nawaz.
Nawaz can elaborate the issues faced.
