### ISSUE TITLE
Auto Deploy

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#25]
Search and enable auto deploy for Login Authentication

**Comment by nawazkh** [comment]
Achieved
Started at 9a4ee5f26186d5ae464ed51d8a6a82318e3666fc
Achieved at 1518203bd50674c0249692c0fab4ca6968499a64

**Comment by pswargam** [comment]
Notes:
Jobs for individual branches are created
A release branch is created which consists of pipeline which will call the individual jobs
