### ISSUE TITLE
Dockerize node js Server

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/Schrodinger-s-cat#29]

**Comment by pswargam** [comment]
Notes:
Initially Dockerfiles 's  files were generated to build images
Later compose files are created to expose ports and network
Later compose is modified to work in swarm cluster

**Comment by ljosyula** [comment]
done in : ceb3a8e137a18398297a8080836129785ea2e115

**Comment by pswargam** [comment]
Following commits fixed issues related to docker:

https://github.com/airavata-courses/Schrodinger-s-cat/commit/04a6faaefe1fe5ef7c16044c10bc27c98a1c8396
