### ISSUE TITLE
Use Postgresql

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#39]
MySQL Server is throwing error on replication. Need to use Postgres sql

**Comment by nawazkh** [comment]
Shifted to Postgresql for login authentication from MySQL Server. MySQL Server unable to docker swarm. 

cd0d2dc11a0f7afa873f68fb3863c995dd72bc71

**Comment by pswargam** [comment]
Notes:

A simple local database was created to verify the connectivity with the existing maven application:
Later it was improvised by Nawaz.
Nawaz can elaborate issues faced
