### ISSUE TITLE
Peer review for Project Milestone 2

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/Schrodinger-s-cat#42]

**Comment by raghu2094** [comment]
Jenkins pipeline is executed after commiting to one branch.  Uses master slave configuration. 
Pipeline consists of building one microservice branch after another. 
All builds passed successful.
Docker Swarm is being used for service discovery which works fine. 
RabbitMQ Mangement UI url was not accessible .
Front end works fine, was able to login , search for recipes and signup. Didn't recieve any mail after successful signup

Questions?
How will you CD pipeline work if I have to make some changes to a particular branch for example Python branch. Do I have to commit to the release_branch and build and deploy all branches everytime a change has been pushed to any of the branches.
What made you opt for  a master -slave configuration in Jenkins.

Feedback:
Apart from asynchronous communication, everything is working fine. Good Job.
Architecture diagram and Implementation details about Service Discovery using Docker Swarm , Messaging using RabbitMQ and Jenkins should have been documented.

**Comment by nawazkh** [comment]
Hello @raghu2094 ,

Thank you for your feedback! 
We have implemented asynchronous communication as a 4th Microservice. 
Upon a new user creation, a email is sent to the user. This is achieved using RabbitMQ producer-consumer concept. 

With your Jenkins credentials, you can try to build the releaseAssignment2 build in Jenkins to test it.

Coming to the documentation, We will update it EOD.

Thanks!

**Comment by nawazkh** [comment]
@ljosyula and @pswargam , We need to update the documentation.
139ffac0561704c21cd4a7a2be6ae02cfb18440b

**Comment by nawazkh** [comment]
Closing the issue since this is completed
