### ISSUE TITLE
RabbitMQ not working in swarm cluster

### ISSUE THREAD

**Issue by siddharthpathak** [airavata-courses/Schrodinger-s-cat#44]
Unable to access RabbitMQ URL in swarm

**Comment by nawazkh** [comment]
Resolved it. 
Error was with creation of network and exposing of port : 1883.
Correct sequence to run a rabbitmq cluster is that. 

- Start a network (overlay)
- Start Listener
- Then once the MQ and listener are up , Start the producer
7fd839dfabef58f1d6feddf4945ced8df7823ddf
7ae1b6ffede7511db8c6ebd137e3f07ee8c2a9d7
