### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by siddharthpathak** [airavata-courses/Schrodinger-s-cat#45]
Jenkins CD working fine using pipeline and master slave. 
Service discovery using Docker swarm works. 
Didn't receive email after sign up .

**Comment by nawazkh** [comment]
Hello @siddharthpathak  ,

Thank you for your feedback!
We have implemented asynchronous communication as a 4th Microservice.
Upon a new user creation, a email is sent to the user. This is achieved using RabbitMQ producer-consumer concept.

With your Jenkins credentials, you can try to build the releaseAssignment2 job in Jenkins to test it.

Thanks!

**Comment by nawazkh** [comment]
Closing issue since it has been implemented and working
