### ISSUE TITLE
Peer Review results

### ISSUE THREAD

**Issue by sagarpanchal8793** [airavata-courses/Schrodinger-s-cat#49]

**Comment by sagarpanchal8793** [comment]
Made commits to test build jenkins and all the builds are successfull

Commits tested for Builds:

682e9a54925b620dd26aba1ac314cda7c8db181c

682806d1181da53441aeafe9041bb6ed2f91dcbf

687dd1b6aac5b0bb31f6a0071f16017c8014dd6e

080212d587333f57ce7b14b42c2f15c539e0151e

0532e20b5c2a0b7d2fb3e9337e71d86691b17d92

5b284d6a2061eb3d44fa57bd58315d6ba008820c

**Comment by sagarpanchal8793** [comment]
No email received upon signup but the UI works great

**Comment by nawazkh** [comment]
Hello @sagarpanchal8793  ,

Thank you for your feedback!
We have implemented asynchronous communication as a 4th Microservice.
Upon a new user creation, a email is sent to the user. This is achieved using RabbitMQ producer-consumer concept.

With your Jenkins credentials, you can try to build the releaseAssignment2 build in Jenkins to test it.
Thanks!

**Comment by nawazkh** [comment]
Closing since no response and issue resolved.
