### ISSUE TITLE
Rename and merge old branches.

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#54]
Hello all,

We need to get rid of branches which are no more being used.
Need to merge them to their base branches.

This may lead to build failure, but we will fix them later. 

We will close this issue once only the 4 micro-services branches exists w.r.t. services in our project.

**Comment by nawazkh** [comment]
all the branches have been refactored to naming conventions

**Comment by nawazkh** [comment]
Done.
0bee04d06fd69efc5278fece9d1a11b729d07cea
45f3179e49b2af0e5b3ec03e51f9f2574c81b441
d16f48e0481dc8259ce962d17a50bbf5a522e111
2908ddbeb984f62a4cb77b98aade138244844222

**Comment by pswargam** [comment]
Done as part of commits: 
da748246fdbfe8d63edf82d337c3198f4537191e
10f7a7e61992266e6e60360098199cf00c152874
6762a78d49c23952141b784b57fae1a26eae0980
