### ISSUE TITLE
Peer Review Assignment 3

### ISSUE THREAD

**Issue by raghu2094** [airavata-courses/Schrodinger-s-cat#69]

**Comment by raghu2094** [comment]
Documentation not updated yet

**Comment by ljosyula** [comment]
We have updated the documentation. Kindly check it now.

**Comment by raghu2094** [comment]
Hi Team,
Here is my feedback after going through the documentation.
All performance metrics and constraints have been well documented and explained. 
From the looks of it, it seems using Docker Swarm makes it easy to handle fault tolerance and load balancing. It's impressive that everything has been dockerized .  

Were you guys able to see how the 4000 requests was distributed over the two nodes. Percentage distribution or any other form to show the distribution?
If it's possible , Can you give the steps to try load testing your application to see the throughput using JMeter. 

Good job on measuring the performance. 
Just one suggestion, looking at the graphs it is unclear what you are trying to infer from them. Some write-up about the graphs would be helpful

**Comment by nawazkh** [comment]
Hey Raghu, 
Thank you for your feedback. 
- We could not find how exactly the requests were being distributed over the nodes. But as per docker's architecture, replicas picked in a round-robin fashion. Unless a module fails, requests would be distributed equally. However, there should be something to measure such statistics, we will check for it and update our wiki.
- Steps to check the output: We were hitting each API individually to check its performance. For Login and retrieve data module, you can setup a test plan to hit a _GET_ request to /jpa/users/get/all-attributes. Port number would be 8888 and IP: http://149.165.170.239
- We will update the logs and what we was tried to imply, will update here once we change the inferences.
