### ISSUE TITLE
Integrate Travis CI

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#7]
Integrate Travis CI with the new branches

**Comment by pswargam** [comment]
Updated the travis files in search and node branches

**Comment by nawazkh** [comment]
Done in 4168010bae8a7edac33eb0d65adab5aff5863af2
d3eeaf671472c6c4f6435948ec2d9c343ed1cbb9
85a9aff383afd902fb4ff0da6406e3a85aeef4cb
