### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by siddharthpathak** [airavata-courses/Schrodinger-s-cat#70]
Please update the documentation for milestone 3.

**Comment by ljosyula** [comment]
We have updated the documentation. Kindly check it now.

**Comment by siddharthpathak** [comment]
Hi,
Nice work with Docker and Docker Swarm. 
Where can I see how did Docker swarm distributed the load? 

Which server did you use for Python, as it can handle 4000 requests at one point?

**Comment by nawazkh** [comment]
Hello Siddharth,

We are currently working on getting the request count for each replica, will soon push it to release. 
You can check the load by running JMeter
Steps:
- We were hitting each API individually to check its performance. For Login and retrieve data module, you can setup a test plan to hit a GET request to /jpa/users/get/all-attributes. Port number would be 8888 and IP: http://149.165.170.239
- To test Search functionality, you can hit a get request to /recipes/pythonSearch/a/ at http://149.165.170.239:8000
