### ISSUE TITLE
Improve Microservices

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#72]
To develop smooth front end. Deliverables front end:
- [x] Improve front end login, signup and over all look
- [x] Improve front end of search
- [x] Display data to users on front end.

Deliverables for Django projects:
- [x] why is the docker image 1.03 GB? we need to scale it down.
- [x] Improve Django search functionality. Check if we need Postgres DB for it. 
- [ ] Implement Elastic search

Deliverables for java Microservices:
- [x] Check how java handles update requests in Django.

**Comment by pswargam** [comment]
Django image is heavy. Probably because we are copying a lot of Data files. Removing them should solve the issue

**Comment by pswargam** [comment]
I have created separate issues for "[Django image is heavy](https://github.com/airavata-courses/Schrodinger-s-cat/issues/76)"
and "[Django Testing](https://github.com/airavata-courses/Schrodinger-s-cat/issues/76)".

**Comment by pswargam** [comment]
Django serach functionality has been modified to support front end

**Comment by nawazkh** [comment]
Front end Dev completed in : 338a6d102a229bfb80a35f6659c6be3e520da9c8
Front end changes confirmed and pulled in : d50dfa3a06fa889be4ca8d90ac9829ca283dde74

**Comment by nawazkh** [comment]
Django - Java problems answered in 166202f34a017f97f33a95e6bddb31b3a7f2d81a

**Comment by nawazkh** [comment]
Elastic search not implemented
