### ISSUE TITLE
Add Travis CI build-passing tag to every branch

### ISSUE THREAD

**Issue by ljosyula** [airavata-courses/Schrodinger-s-cat#73]
We cannot see if the build of a branch is passing or not, there is no build-passing tag in the branches except in Java login authentication service.

We need to add the build-passing tag to every branch

**Comment by pswargam** [comment]
Our builds are always successful and it is visible in travis.
What is a build passing tag?

**Comment by pswargam** [comment]
It is done now. It is a tag in readme which says that travis build is successful
