### ISSUE TITLE
Kubernetes Pods rc and service for node Microservice

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/Schrodinger-s-cat#82]

**Comment by pswargam** [comment]
Added pods rc and service

**Comment by pswargam** [comment]
Inititlaly , we implemented pods and rc seperately. WE later implemented deployments .

Done as part of 489847cc5132d854c5c9ad9c813f4d42d1e814fb

**Comment by nawazkh** [comment]
Refer # 102
