### ISSUE TITLE
Kubernetes Pods rc and service for front end

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/Schrodinger-s-cat#83]

**Comment by ljosyula** [comment]
done in: bdc62bb0787b18a7807851c11bfdeb83896d9e07 
and 166202f34a017f97f33a95e6bddb31b3a7f2d81a

**Comment by pswargam** [comment]
Inititlaly , we implemented pods and rc seperately. WE later implemented deployments .The above commits will have deployments.

**Comment by nawazkh** [comment]
Refer #102
