### ISSUE TITLE
Install Jenkins on TACC instance

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/Schrodinger-s-cat#86]

**Comment by pswargam** [comment]
Installled jenkins on scat-jenkins-master

**Comment by pswargam** [comment]
added jenkins and docker to sudoers

**Comment by pswargam** [comment]
We have changed the installations and installed it on scat_kube2

**Comment by nawazkh** [comment]
Done in d9198c4d8f7aa751b2e6b33963dda4091bc8c54e
