### ISSUE TITLE
Jenkins file to work with new instance

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/Schrodinger-s-cat#87]
We will try to minimize steps in this Jenkins file.

My thoughts on an Ideals Jenkins file:
1)Clears old pods,Replication controllers and services
2)Will not build images in the server
3)Will use image from the docker hub to build pods

**Comment by ljosyula** [comment]
for login and login DB done in : d8de6c1f3d3546de98d87834d8d5b715fbf0ace6
for front end done in : bdc62bb0787b18a7807851c11bfdeb83896d9e07

**Comment by pswargam** [comment]
Search done in :

**Comment by pswargam** [comment]
Search done in : 80698a81e41421407faa3d93dfd6c1902ea11f30
