### ISSUE TITLE
Create a Better UI

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#88]
Current UI works well, but needs improvement.

We have started working on a newer version of the UI.
It is easy to understand and has stateless support to the project.

90% completed at 55f38b0362badd5a0cbb9156b60567be7bb4ee59

**Comment by pswargam** [comment]
Peer programmed with nawaz on this

**Comment by ljosyula** [comment]
worked together on this

**Comment by ljosyula** [comment]
done in : ee173f988a753580ccfe885d7a75f2ddb714ee17
