### ISSUE TITLE
Issue while creating replicas for postgres in Kubernetes

### ISSUE THREAD

**Issue by ljosyula** [airavata-courses/Schrodinger-s-cat#90]
When we are trying to create the replicas for postgres, all the pods are in running status but the server is not up.
It is logging the following comments: "Shutting down the server" "Server ready to take requests"

**Comment by ljosyula** [comment]
The issue was resolved after updating the version of Postgres as the current version of this framework is not stable for Postgres Operator Framework

**Comment by nawazkh** [comment]
Closing this issue
