### ISSUE TITLE
Update wiki page

### ISSUE THREAD

**Issue by sagarpanchal8793** [airavata-courses/Schrodinger-s-cat#97]
I visited the Assignment-4 page and i think you are in the process of updating it. Kindly let me know, once you are done with it.

**Comment by nawazkh** [comment]
Hello Sagar, 

We are still updating it. We will let you know once is it done. 

Thanks,
Nawaz

**Comment by nawazkh** [comment]
Hello Sagar, 

Our application is up and running if you want to test it. 
The link is mentioned in the assignment 4. 

Also, you can check our dashboard for Kubernetes installation. You will need the admin token for login.
We will get it to you in personal chat once you ping us.


All the documentation and wiki will be done soon.

Thanks,
nawaz

**Comment by sagarpanchal8793** [comment]
Nice work, I was able to signup, login and check the website, UI is great and also verified the builds by committing in every branch, pods are being created by Kubernetes. Overall effort is really great. All the best and keep up the good work.

**Comment by sagarpanchal8793** [comment]
442595971dc8f1746237c40bb7830234b8996726

67ba4e58dcd54182772e3e728b3fa40963217915

60fc63bfb7f4d0dbb1874258ee03d3e4d6987a83

89ecf60bf98010e88f6cba2c4e4db71b514206bf
