### ISSUE TITLE
Documentation for project 4

### ISSUE THREAD

**Issue by pswargam** [airavata-courses/Schrodinger-s-cat#98]

**Comment by pswargam** [comment]
Written Setup steps, evolution of project, MAjor issues. Nawaz will  review

**Comment by ljosyula** [comment]
done from e7629db to b553429  (wiki history)

and cf9c4c3abb96d24ea4ff4613b6601a59ff15325c , 167dc8aedb07cd62338ad26e4adf915a3ab7d7be , 26551fcde0bf53f605490a3eac7df969850be2a7
