### ISSUE TITLE
Convert the login application to a Stateless service from a stateful one.

### ISSUE THREAD

**Issue by nawazkh** [airavata-courses/Schrodinger-s-cat#99]
We faced problems with maintaining user session when the login service was a stateful one. 
* On replicating the user service in docker swarm and Kubernetes, user's session was not properly handled.
* This lead to user being logout and then also remain logged-in in some replicated instance.

**Comment by ljosyula** [comment]
done in : 7c8095d0488badeaf9c2f7b980f310e31a9acbd5
